/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.js'
import { Route as IndexRouteImport } from './routes/index.js'
import { Route as AppIndexRouteImport } from './routes/app.index.js'
import { Route as AppSetupRouteImport } from './routes/app.setup.js'
import { Route as AppInstallationsInstallationIdRouteImport } from './routes/app.installations.$installationId.js'
import { Route as ROwnerRepoIndexRouteImport } from './routes/r.$owner.$repo.index.js'
import { Route as ROwnerRepoSettingsRouteImport } from './routes/r.$owner.$repo.settings.js'
import { Route as ROwnerRepoHistoryRouteImport } from './routes/r.$owner.$repo.history.js'
import { Route as ROwnerRepoCompareRouteImport } from './routes/r.$owner.$repo.compare.js'
import { Route as ROwnerRepoSettingsSyntheticScenariosRouteImport } from './routes/r.$owner.$repo.settings.synthetic-scenarios.js'
import { Route as ROwnerRepoScenariosScenarioRouteImport } from './routes/r.$owner.$repo.scenarios.$scenario.js'
import { Route as ROwnerRepoSettingsSyntheticScenariosNewRouteImport } from './routes/r.$owner.$repo.settings.synthetic-scenarios.new.js'
import { Route as ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRouteImport } from './routes/r.$owner.$repo.settings.synthetic-scenarios.$scenarioId.edit.js'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/app/setup',
  path: '/app/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInstallationsInstallationIdRoute =
  AppInstallationsInstallationIdRouteImport.update({
    id: '/app/installations/$installationId',
    path: '/app/installations/$installationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ROwnerRepoIndexRoute = ROwnerRepoIndexRouteImport.update({
  id: '/r/$owner/$repo/',
  path: '/r/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoSettingsRoute = ROwnerRepoSettingsRouteImport.update({
  id: '/r/$owner/$repo/settings',
  path: '/r/$owner/$repo/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoHistoryRoute = ROwnerRepoHistoryRouteImport.update({
  id: '/r/$owner/$repo/history',
  path: '/r/$owner/$repo/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoCompareRoute = ROwnerRepoCompareRouteImport.update({
  id: '/r/$owner/$repo/compare',
  path: '/r/$owner/$repo/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoSettingsSyntheticScenariosRoute =
  ROwnerRepoSettingsSyntheticScenariosRouteImport.update({
    id: '/synthetic-scenarios',
    path: '/synthetic-scenarios',
    getParentRoute: () => ROwnerRepoSettingsRoute,
  } as any)
const ROwnerRepoScenariosScenarioRoute =
  ROwnerRepoScenariosScenarioRouteImport.update({
    id: '/r/$owner/$repo/scenarios/$scenario',
    path: '/r/$owner/$repo/scenarios/$scenario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ROwnerRepoSettingsSyntheticScenariosNewRoute =
  ROwnerRepoSettingsSyntheticScenariosNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ROwnerRepoSettingsSyntheticScenariosRoute,
  } as any)
const ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRoute =
  ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRouteImport.update({
    id: '/$scenarioId/edit',
    path: '/$scenarioId/edit',
    getParentRoute: () => ROwnerRepoSettingsSyntheticScenariosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/setup': typeof AppSetupRoute
  '/app/': typeof AppIndexRoute
  '/app/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/r/$owner/$repo/compare': typeof ROwnerRepoCompareRoute
  '/r/$owner/$repo/history': typeof ROwnerRepoHistoryRoute
  '/r/$owner/$repo/settings': typeof ROwnerRepoSettingsRouteWithChildren
  '/r/$owner/$repo/': typeof ROwnerRepoIndexRoute
  '/r/$owner/$repo/scenarios/$scenario': typeof ROwnerRepoScenariosScenarioRoute
  '/r/$owner/$repo/settings/synthetic-scenarios': typeof ROwnerRepoSettingsSyntheticScenariosRouteWithChildren
  '/r/$owner/$repo/settings/synthetic-scenarios/new': typeof ROwnerRepoSettingsSyntheticScenariosNewRoute
  '/r/$owner/$repo/settings/synthetic-scenarios/$scenarioId/edit': typeof ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/setup': typeof AppSetupRoute
  '/app': typeof AppIndexRoute
  '/app/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/r/$owner/$repo/compare': typeof ROwnerRepoCompareRoute
  '/r/$owner/$repo/history': typeof ROwnerRepoHistoryRoute
  '/r/$owner/$repo/settings': typeof ROwnerRepoSettingsRouteWithChildren
  '/r/$owner/$repo': typeof ROwnerRepoIndexRoute
  '/r/$owner/$repo/scenarios/$scenario': typeof ROwnerRepoScenariosScenarioRoute
  '/r/$owner/$repo/settings/synthetic-scenarios': typeof ROwnerRepoSettingsSyntheticScenariosRouteWithChildren
  '/r/$owner/$repo/settings/synthetic-scenarios/new': typeof ROwnerRepoSettingsSyntheticScenariosNewRoute
  '/r/$owner/$repo/settings/synthetic-scenarios/$scenarioId/edit': typeof ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/setup': typeof AppSetupRoute
  '/app/': typeof AppIndexRoute
  '/app/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/r/$owner/$repo/compare': typeof ROwnerRepoCompareRoute
  '/r/$owner/$repo/history': typeof ROwnerRepoHistoryRoute
  '/r/$owner/$repo/settings': typeof ROwnerRepoSettingsRouteWithChildren
  '/r/$owner/$repo/': typeof ROwnerRepoIndexRoute
  '/r/$owner/$repo/scenarios/$scenario': typeof ROwnerRepoScenariosScenarioRoute
  '/r/$owner/$repo/settings/synthetic-scenarios': typeof ROwnerRepoSettingsSyntheticScenariosRouteWithChildren
  '/r/$owner/$repo/settings/synthetic-scenarios/new': typeof ROwnerRepoSettingsSyntheticScenariosNewRoute
  '/r/$owner/$repo/settings/synthetic-scenarios/$scenarioId/edit': typeof ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/setup'
    | '/app/'
    | '/app/installations/$installationId'
    | '/r/$owner/$repo/compare'
    | '/r/$owner/$repo/history'
    | '/r/$owner/$repo/settings'
    | '/r/$owner/$repo/'
    | '/r/$owner/$repo/scenarios/$scenario'
    | '/r/$owner/$repo/settings/synthetic-scenarios'
    | '/r/$owner/$repo/settings/synthetic-scenarios/new'
    | '/r/$owner/$repo/settings/synthetic-scenarios/$scenarioId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/setup'
    | '/app'
    | '/app/installations/$installationId'
    | '/r/$owner/$repo/compare'
    | '/r/$owner/$repo/history'
    | '/r/$owner/$repo/settings'
    | '/r/$owner/$repo'
    | '/r/$owner/$repo/scenarios/$scenario'
    | '/r/$owner/$repo/settings/synthetic-scenarios'
    | '/r/$owner/$repo/settings/synthetic-scenarios/new'
    | '/r/$owner/$repo/settings/synthetic-scenarios/$scenarioId/edit'
  id:
    | '__root__'
    | '/'
    | '/app/setup'
    | '/app/'
    | '/app/installations/$installationId'
    | '/r/$owner/$repo/compare'
    | '/r/$owner/$repo/history'
    | '/r/$owner/$repo/settings'
    | '/r/$owner/$repo/'
    | '/r/$owner/$repo/scenarios/$scenario'
    | '/r/$owner/$repo/settings/synthetic-scenarios'
    | '/r/$owner/$repo/settings/synthetic-scenarios/new'
    | '/r/$owner/$repo/settings/synthetic-scenarios/$scenarioId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppSetupRoute: typeof AppSetupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInstallationsInstallationIdRoute: typeof AppInstallationsInstallationIdRoute
  ROwnerRepoCompareRoute: typeof ROwnerRepoCompareRoute
  ROwnerRepoHistoryRoute: typeof ROwnerRepoHistoryRoute
  ROwnerRepoSettingsRoute: typeof ROwnerRepoSettingsRouteWithChildren
  ROwnerRepoIndexRoute: typeof ROwnerRepoIndexRoute
  ROwnerRepoScenariosScenarioRoute: typeof ROwnerRepoScenariosScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/app/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/installations/$installationId': {
      id: '/app/installations/$installationId'
      path: '/app/installations/$installationId'
      fullPath: '/app/installations/$installationId'
      preLoaderRoute: typeof AppInstallationsInstallationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/': {
      id: '/r/$owner/$repo/'
      path: '/r/$owner/$repo'
      fullPath: '/r/$owner/$repo/'
      preLoaderRoute: typeof ROwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/settings': {
      id: '/r/$owner/$repo/settings'
      path: '/r/$owner/$repo/settings'
      fullPath: '/r/$owner/$repo/settings'
      preLoaderRoute: typeof ROwnerRepoSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/history': {
      id: '/r/$owner/$repo/history'
      path: '/r/$owner/$repo/history'
      fullPath: '/r/$owner/$repo/history'
      preLoaderRoute: typeof ROwnerRepoHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/compare': {
      id: '/r/$owner/$repo/compare'
      path: '/r/$owner/$repo/compare'
      fullPath: '/r/$owner/$repo/compare'
      preLoaderRoute: typeof ROwnerRepoCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/settings/synthetic-scenarios': {
      id: '/r/$owner/$repo/settings/synthetic-scenarios'
      path: '/synthetic-scenarios'
      fullPath: '/r/$owner/$repo/settings/synthetic-scenarios'
      preLoaderRoute: typeof ROwnerRepoSettingsSyntheticScenariosRouteImport
      parentRoute: typeof ROwnerRepoSettingsRoute
    }
    '/r/$owner/$repo/scenarios/$scenario': {
      id: '/r/$owner/$repo/scenarios/$scenario'
      path: '/r/$owner/$repo/scenarios/$scenario'
      fullPath: '/r/$owner/$repo/scenarios/$scenario'
      preLoaderRoute: typeof ROwnerRepoScenariosScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/settings/synthetic-scenarios/new': {
      id: '/r/$owner/$repo/settings/synthetic-scenarios/new'
      path: '/new'
      fullPath: '/r/$owner/$repo/settings/synthetic-scenarios/new'
      preLoaderRoute: typeof ROwnerRepoSettingsSyntheticScenariosNewRouteImport
      parentRoute: typeof ROwnerRepoSettingsSyntheticScenariosRoute
    }
    '/r/$owner/$repo/settings/synthetic-scenarios/$scenarioId/edit': {
      id: '/r/$owner/$repo/settings/synthetic-scenarios/$scenarioId/edit'
      path: '/$scenarioId/edit'
      fullPath: '/r/$owner/$repo/settings/synthetic-scenarios/$scenarioId/edit'
      preLoaderRoute: typeof ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRouteImport
      parentRoute: typeof ROwnerRepoSettingsSyntheticScenariosRoute
    }
  }
}

interface ROwnerRepoSettingsSyntheticScenariosRouteChildren {
  ROwnerRepoSettingsSyntheticScenariosNewRoute: typeof ROwnerRepoSettingsSyntheticScenariosNewRoute
  ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRoute: typeof ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRoute
}

const ROwnerRepoSettingsSyntheticScenariosRouteChildren: ROwnerRepoSettingsSyntheticScenariosRouteChildren =
  {
    ROwnerRepoSettingsSyntheticScenariosNewRoute:
      ROwnerRepoSettingsSyntheticScenariosNewRoute,
    ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRoute:
      ROwnerRepoSettingsSyntheticScenariosScenarioIdEditRoute,
  }

const ROwnerRepoSettingsSyntheticScenariosRouteWithChildren =
  ROwnerRepoSettingsSyntheticScenariosRoute._addFileChildren(
    ROwnerRepoSettingsSyntheticScenariosRouteChildren,
  )

interface ROwnerRepoSettingsRouteChildren {
  ROwnerRepoSettingsSyntheticScenariosRoute: typeof ROwnerRepoSettingsSyntheticScenariosRouteWithChildren
}

const ROwnerRepoSettingsRouteChildren: ROwnerRepoSettingsRouteChildren = {
  ROwnerRepoSettingsSyntheticScenariosRoute:
    ROwnerRepoSettingsSyntheticScenariosRouteWithChildren,
}

const ROwnerRepoSettingsRouteWithChildren =
  ROwnerRepoSettingsRoute._addFileChildren(ROwnerRepoSettingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppSetupRoute: AppSetupRoute,
  AppIndexRoute: AppIndexRoute,
  AppInstallationsInstallationIdRoute: AppInstallationsInstallationIdRoute,
  ROwnerRepoCompareRoute: ROwnerRepoCompareRoute,
  ROwnerRepoHistoryRoute: ROwnerRepoHistoryRoute,
  ROwnerRepoSettingsRoute: ROwnerRepoSettingsRouteWithChildren,
  ROwnerRepoIndexRoute: ROwnerRepoIndexRoute,
  ROwnerRepoScenariosScenarioRoute: ROwnerRepoScenariosScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
