/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.js'
import { Route as IndexRouteImport } from './routes/index.js'
import { Route as AppIndexRouteImport } from './routes/app.index.js'
import { Route as AppSetupRouteImport } from './routes/app.setup.js'
import { Route as AppInstallationsInstallationIdRouteImport } from './routes/app.installations.$installationId.js'
import { Route as ROwnerRepoIndexRouteImport } from './routes/r.$owner.$repo.index.js'
import { Route as ROwnerRepoSettingsRouteImport } from './routes/r.$owner.$repo.settings.js'
import { Route as ROwnerRepoCompareRouteImport } from './routes/r.$owner.$repo.compare.js'
import { Route as ROwnerRepoScenariosScenarioRouteImport } from './routes/r.$owner.$repo.scenarios.$scenario.js'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/app/setup',
  path: '/app/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInstallationsInstallationIdRoute =
  AppInstallationsInstallationIdRouteImport.update({
    id: '/app/installations/$installationId',
    path: '/app/installations/$installationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ROwnerRepoIndexRoute = ROwnerRepoIndexRouteImport.update({
  id: '/r/$owner/$repo/',
  path: '/r/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoSettingsRoute = ROwnerRepoSettingsRouteImport.update({
  id: '/r/$owner/$repo/settings',
  path: '/r/$owner/$repo/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoCompareRoute = ROwnerRepoCompareRouteImport.update({
  id: '/r/$owner/$repo/compare',
  path: '/r/$owner/$repo/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoScenariosScenarioRoute =
  ROwnerRepoScenariosScenarioRouteImport.update({
    id: '/r/$owner/$repo/scenarios/$scenario',
    path: '/r/$owner/$repo/scenarios/$scenario',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/setup': typeof AppSetupRoute
  '/app/': typeof AppIndexRoute
  '/app/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/r/$owner/$repo/compare': typeof ROwnerRepoCompareRoute
  '/r/$owner/$repo/settings': typeof ROwnerRepoSettingsRoute
  '/r/$owner/$repo/': typeof ROwnerRepoIndexRoute
  '/r/$owner/$repo/scenarios/$scenario': typeof ROwnerRepoScenariosScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/setup': typeof AppSetupRoute
  '/app': typeof AppIndexRoute
  '/app/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/r/$owner/$repo/compare': typeof ROwnerRepoCompareRoute
  '/r/$owner/$repo/settings': typeof ROwnerRepoSettingsRoute
  '/r/$owner/$repo': typeof ROwnerRepoIndexRoute
  '/r/$owner/$repo/scenarios/$scenario': typeof ROwnerRepoScenariosScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/setup': typeof AppSetupRoute
  '/app/': typeof AppIndexRoute
  '/app/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/r/$owner/$repo/compare': typeof ROwnerRepoCompareRoute
  '/r/$owner/$repo/settings': typeof ROwnerRepoSettingsRoute
  '/r/$owner/$repo/': typeof ROwnerRepoIndexRoute
  '/r/$owner/$repo/scenarios/$scenario': typeof ROwnerRepoScenariosScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/setup'
    | '/app/'
    | '/app/installations/$installationId'
    | '/r/$owner/$repo/compare'
    | '/r/$owner/$repo/settings'
    | '/r/$owner/$repo/'
    | '/r/$owner/$repo/scenarios/$scenario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/setup'
    | '/app'
    | '/app/installations/$installationId'
    | '/r/$owner/$repo/compare'
    | '/r/$owner/$repo/settings'
    | '/r/$owner/$repo'
    | '/r/$owner/$repo/scenarios/$scenario'
  id:
    | '__root__'
    | '/'
    | '/app/setup'
    | '/app/'
    | '/app/installations/$installationId'
    | '/r/$owner/$repo/compare'
    | '/r/$owner/$repo/settings'
    | '/r/$owner/$repo/'
    | '/r/$owner/$repo/scenarios/$scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppSetupRoute: typeof AppSetupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInstallationsInstallationIdRoute: typeof AppInstallationsInstallationIdRoute
  ROwnerRepoCompareRoute: typeof ROwnerRepoCompareRoute
  ROwnerRepoSettingsRoute: typeof ROwnerRepoSettingsRoute
  ROwnerRepoIndexRoute: typeof ROwnerRepoIndexRoute
  ROwnerRepoScenariosScenarioRoute: typeof ROwnerRepoScenariosScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/app/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/installations/$installationId': {
      id: '/app/installations/$installationId'
      path: '/app/installations/$installationId'
      fullPath: '/app/installations/$installationId'
      preLoaderRoute: typeof AppInstallationsInstallationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/': {
      id: '/r/$owner/$repo/'
      path: '/r/$owner/$repo'
      fullPath: '/r/$owner/$repo/'
      preLoaderRoute: typeof ROwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/settings': {
      id: '/r/$owner/$repo/settings'
      path: '/r/$owner/$repo/settings'
      fullPath: '/r/$owner/$repo/settings'
      preLoaderRoute: typeof ROwnerRepoSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/compare': {
      id: '/r/$owner/$repo/compare'
      path: '/r/$owner/$repo/compare'
      fullPath: '/r/$owner/$repo/compare'
      preLoaderRoute: typeof ROwnerRepoCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/scenarios/$scenario': {
      id: '/r/$owner/$repo/scenarios/$scenario'
      path: '/r/$owner/$repo/scenarios/$scenario'
      fullPath: '/r/$owner/$repo/scenarios/$scenario'
      preLoaderRoute: typeof ROwnerRepoScenariosScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppSetupRoute: AppSetupRoute,
  AppIndexRoute: AppIndexRoute,
  AppInstallationsInstallationIdRoute: AppInstallationsInstallationIdRoute,
  ROwnerRepoCompareRoute: ROwnerRepoCompareRoute,
  ROwnerRepoSettingsRoute: ROwnerRepoSettingsRoute,
  ROwnerRepoIndexRoute: ROwnerRepoIndexRoute,
  ROwnerRepoScenariosScenarioRoute: ROwnerRepoScenariosScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
